// @ts-nocheck
import { DurableObject } from "cloudflare:workers";
// Generated by the OpenNext build.
// @ts-ignore
import nextHandler from "./.open-next/worker.js";

interface Env {
  STATE_STORE: DurableObjectNamespace<StateStore>;
}

export class StateStore extends DurableObject<Env> {
  async fetch(request: Request): Promise<Response> {
    if (request.method === "GET") {
      const state = await this.ctx.storage.get("irontrack-state");
      return Response.json({ state: state ?? null });
    }

    if (request.method === "POST") {
      const state = await request.json();
      await this.ctx.storage.put("irontrack-state", state);
      return Response.json({ saved: true, savedAt: new Date().toISOString() });
    }

    return new Response("Method not allowed", { status: 405 });
  }
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname === "/api/state") {
      const id = env.STATE_STORE.idFromName("owner");
      return env.STATE_STORE.get(id).fetch(request);
    }
    return nextHandler.fetch(request, env, ctx);
  },
};
